### ISSUE TITLE
TRIGGERS for FTS5 cause panic

### ISSUE THREAD

**Issue by ayhangenc** [mattn/go-sqlite3#1112]
Hello,

I'm trying to implement FTS5 on top of my DB. Everything is OK on SQL console (using Goland IDE) but when I run the SQL INSERT from go app, I have a panic;

[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x40ecc42]

goroutine 1 [running]:
database/sql.(*Stmt).ExecContext(0x0, {0x458fe10, 0xc000118000}, {0xc000179bc0, 0x6, 0x6})
        /usr/local/go/src/database/sql/sql.go:2619 +0x82
database/sql.(*Stmt).Exec(...)
        /usr/local/go/src/database/sql/sql.go:2651
main.parseKAP({0xc0000200a0, 0xc}, 0xc000179e28?, 0x45090b8?)
        /Users/xxxx/GolandProjects/xxxx.1002/bin/xxx.go:229 +0x9b7

my go code is:
`
	insertQ, err := dbX.Prepare("INSERT INTO XX_X('ID', 'KK', 'YZ', 'BB', 'NN', 'EE') VALUES (?,?,?,?,?,?)")

	if err != nil {

		log.Println("XX DB Insert: insertQ error!", err)

	}

	_, err = insertQ.Exec(i, kk, yz, bb, nn, k)

	if err != nil {

`

this codes run OK with the same DB initialized for FTS5 by creating VT

`
create table XX_X
(
    ID          INTEGER
        constraint XX_X_pk
            primary key,
    KK       TEXT,
    YZ       datetime,
    BB      TEXT,
    NN      TEXT,
    EE       INTEGER
);
`

`
CREATE VIRTUAL TABLE XX_FTS5 USING fts5
(
    KK,
    BB,
    NN,
    content='XX_X',
    content_rowid='ID'
`

but after creating trıggers, I got panic message, here are the triggers

`
CREATE TRIGGER XX_X_FTS5_AI AFTER INSERT ON XX_X BEGIN
    INSERT INTO XX_X_FTS5(
        rowid,
        KK,
        BB,
        NN
    )
    VALUES(
        new.ID,
        new.KK,
        new.BB,
        new.NN
          );
END;
`

`
CREATE TRIGGER XX_X_FTS5_AU AFTER UPDATE OF KK, BB, NN ON XX_X BEGIN
    UPDATE XX_X_FTS5 SET
        KK = new.KK,
        BB = new.BB,
        NN = new.NN
    WHERE rowid = old.ID;
END;
`

`
CREATE TRIGGER XX_X_FTS5_AD AFTER DELETE ON XX_X BEGIN
    DELETE FROM XX_X_FTS5 WHERE rowid = old.ID;
END;
`

version info

`
go version go1.19.1 darwin/amd64
`

`
SQLite version 3.37.0 2021-12-09 01:34:53
`

`
go-sqlite3@v1.14.16
`

your suggestions appreciated...

**Comment by rittneje** [comment]
Your code is panicking because you are calling `Exec` on a nil `sql.Stmt`. Based upon the code you shared, this is likely because `db.Prepare` returned an error. Since you only logged the error but did not return, it continues on the next line but `insertQ` is `nil`.

**Comment by ayhangenc** [comment]
Hey rittneje,

Thanks for the prompt comment.
Sorry about the formatting, my first post here ...
I see your point, `nil` is what I get. The problem, the same code is running on the very same DB table without any problem if I drop the `INSERT` trigger. The one I need is on my first message, to enable FTS5. Actually any `INSERT`  is causing panic. no matter if it's related to my virtual FTS table or any other table I test. On the other hand the `insertQ` is running OK on server query console. That's why I'm suspicious about go-sqlite3. I would test with mysql to see if it's OK and to narrow my research.
Hope this clarifies my case.

Thanks...

**Comment by rittneje** [comment]
What error does `dbX.Prepare` return?
