### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wenerme** [mattn/go-sqlite3#192]
Trace
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x59e48]

goroutine 1 [running]:
database/sql.(*DB).Close(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:475 +0x448
database/sql.(*DB).conn(0x0, 0x200000000000031, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:634 +0x7ae
database/sql.(*DB).exec(0x0, 0x1589d0, 0x51, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:884 +0x96
database/sql.(*DB).Exec(0x0, 0x1589d0, 0x51, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/database/sql/sql.go:875 +0xcd
```

Code
```
import (
    "log"
    "fmt"
    "database/sql"
    "os"
)

func main() {
    os.Remove("./sqlite.db")
    db, err := sql.Open("sqlite3", "./sqlite.db")
    must(err)
    defer db.Close()

    db.Exec(`create table if not exists user (id  integer not null primary key,name text, age integer)`)
    tx,err := db.Begin()
    must(err)
    tx.Exec(`insert into user(id,name,age) values(1,'wener',20)`)
    tx.Exec(`insert into user(id,name,age) values(2,'xxx',18)`)
    tx.Commit()

    rows,err := db.Query(`select * from user`)
    must(err)

    for  {
        if !rows.Next() {
            break
        }
        col,err := rows.Columns()
        must(err)
        for c:=range col{
            fmt.Println(c)
        }
    }

}

func must(err error) {
    if err == nil {
        log.Fatal(err)
    }
}
```

**Comment by wenerme** [comment]
```
# go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by mattn** [comment]
Because you don't import `go-sqlite3`.

**Comment by mattn** [comment]
```go
import (
    "log"
    "fmt"
    "database/sql"
    "os"
    _ "github.com/mattn/go-sqlite" // Add This
)
```

**Comment by wenerme** [comment]
Should be `github.com/mattn/go-sqlite3` :smile: ?

**Comment by mattn** [comment]
yep :smile:

**Comment by ramankeswani** [comment]
Hey I am facing the same issue even after import. Can you please suggest?
`package main

import (
	"database/sql"
	"os"

	_ "github.com/mattn/go-sqlite3"
)

func main() {
	os.Remove("./nraboy.db")
	database, _ := sql.Open("sqlite3", "./nraboy.db")
	statement, _ := database.Prepare("CREATE TABLE ID NOT EXISTS people(id INTEGER PRIMARY KEY, firstname TEXT, lastname TEXT")
	statement.Exec()
}
`
