### ISSUE TITLE
Tests don't pass with runtime.GOMAXPROCS(2).

### ISSUE THREAD

**Issue by sbunce** [mattn/go-sqlite3#216]
If you add this at the top of sqltest.go then tests fail. I reproduced this on tip and go1.4.
```
func init() {
	runtime.GOMAXPROCS(2)
}
```

Here's the error.
```
sbunce@obsidian:~/go/src/local$ go test github.com/mattn...
--- FAIL: TestPreparedStmt (0.00s)
	sqltest.go:292: Query: no such table: t
	sqltest.go:292: Query: no such table: t
	sqltest.go:296: Insert: no such table: t
	sqltest.go:292: Query: no such table: t
	sqltest.go:292: Query: no such table: t
	sqltest.go:292: Query: no such table: t
	sqltest.go:292: Query: no such table: t
	sqltest.go:292: Query: no such table: t
	sqltest.go:296: Insert: no such table: t
	sqltest.go:296: Insert: no such table: t
BenchmarkExec           500000     373728 req/s
BenchmarkQuery          200000     101107 req/s
BenchmarkParams         200000      82785 req/s
BenchmarkStmt           200000     117583 req/s
BenchmarkRows       panic: no such table: bench

goroutine 74 [running]:
github.com/mattn/go-sqlite3/sqlite3_test.makeBench()
	/home/sbunce/go/src/github.com/mattn/go-sqlite3/sqlite3_test/sqltest.go:147 +0x138
sync.(*Once).Do(0xc8200f83a8, 0x7223b8)
	/home/sbunce/src/go/src/sync/once.go:44 +0xe4
github.com/mattn/go-sqlite3/sqlite3_test.BenchmarkRows(0xc82022a000)
	/home/sbunce/go/src/github.com/mattn/go-sqlite3/sqlite3_test/sqltest.go:366 +0x5d
testing.(*B).runN(0xc82022a000, 0x1)
	/home/sbunce/src/go/src/testing/benchmark.go:124 +0x9a
testing.(*B).launch(0xc82022a000)
	/home/sbunce/src/go/src/testing/benchmark.go:199 +0x63
created by testing.(*B).run
	/home/sbunce/src/go/src/testing/benchmark.go:179 +0x54

goroutine 1 [chan receive]:
testing.RunTests(0x7223c8, 0x9de600, 0x1d, 0x1d, 0xc82000e201)
	/home/sbunce/src/go/src/testing/testing.go:561 +0x8ad
testing.(*M).Run(0xc820045f08, 0x66e701)
	/home/sbunce/src/go/src/testing/testing.go:493 +0x70
main.main()
	github.com/mattn/go-sqlite3/_test/_testmain.go:110 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/sbunce/src/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 52 [runnable]:
testing.(*B).run(0xc82022a000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sbunce/src/go/src/testing/benchmark.go:180 +0x7b
testing.Benchmark(0x722368, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sbunce/src/go/src/testing/benchmark.go:465 +0xc7
github.com/mattn/go-sqlite3/sqlite3_test.RunTests(0xc8200a9050, 0xc8200e4320, 0x0)
	/home/sbunce/go/src/github.com/mattn/go-sqlite3/sqlite3_test/sqltest.go:63 +0x2a3
github.com/mattn/go-sqlite3.TestSuite(0xc8200a9050)
	/home/sbunce/go/src/github.com/mattn/go-sqlite3/sqlite3_test.go:778 +0x179
testing.tRunner(0xc8200a9050, 0x9de7e0)
	/home/sbunce/src/go/src/testing/testing.go:455 +0x98
created by testing.RunTests
	/home/sbunce/src/go/src/testing/testing.go:560 +0x86d

goroutine 53 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8200e4320)
	/home/sbunce/src/go/src/database/sql/sql.go:623 +0x45
created by database/sql.Open
	/home/sbunce/src/go/src/database/sql/sql.go:470 +0x30a
FAIL	github.com/mattn/go-sqlite3	8.022s
?   	github.com/mattn/go-sqlite3/sqlite3_test	[no test files]
```

https://github.com/mattn/go-sqlite3/blob/master/sqlite3_test/sqltest.go#L287

**Comment by mattn** [comment]
Because connection doesn't have exclusion.
https://github.com/mattn/go-sqlite3/blob/master/sqlite3_test.go#L772
