### ISSUE TITLE
fts5 seg fault

### ISSUE THREAD

**Issue by gaillard** [mattn/go-sqlite3#388]
Not sure what is causing this but I am running an FTS5 search.

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x1a773bf, 0x2a)
	/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 438 [syscall, locked to thread]:
runtime.cgocall(0xc5e5e0, 0xc420175320, 0x7fd692e4a6a0)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc4201752f0 sp=0xc4201752b0
XXX/vendor/XXX/exf/go-sqlite3._Cfunc_sqlite3_step(0x7fd66000a568, 0x7fd600000000)
	XXX/vendor/XXX/exf/go-sqlite3/_obj/_cgo_gotypes.go:831 +0x49 fp=0xc420175320 sp=0xc4201752f0
XXX/vendor/XXX/exf/go-sqlite3.(*SQLiteRows).Next.func1(0x7fd66000a568, 0x7fd692e09505)
	/home/gaillard/go/src/XXX/vendor/XXX/exf/go-sqlite3/sqlite3.go:886 +0x60 fp=0xc420175358 sp=0xc420175320
XXX/vendor/XXX/exf/go-sqlite3.(*SQLiteRows).Next(0xc4204f6320, 0xc4205de700, 0x38, 0x38, 0x38, 0x38)
	/home/gaillard/go/src/XXX/vendor/XXX/exf/go-sqlite3/sqlite3.go:886 +0x5d fp=0xc4201754f0 sp=0xc420175358
database/sql.(*Rows).nextLocked(0xc420352180, 0xc420175568)
	/usr/local/go/src/database/sql/sql.go:2149 +0x6c fp=0xc420175530 sp=0xc4201754f0
database/sql.(*Rows).Next.func1()
	/usr/local/go/src/database/sql/sql.go:2134 +0x3c fp=0xc420175560 sp=0xc420175530
database/sql.withLock(0x2503e40, 0xc4203521b0, 0xc4201755a8)
	/usr/local/go/src/database/sql/sql.go:2545 +0x65 fp=0xc420175588 sp=0xc420175560
database/sql.(*Rows).Next(0xc420352180, 0x1a89280)
	/usr/local/go/src/database/sql/sql.go:2135 +0x83 fp=0xc4201755d8 sp=0xc420175588

```

**Comment by gaillard** [comment]
I've narrowed this down to a `%` in a fts5 column and then running any query. Is there some kind of limit for the kinds of characters that can go into fts5 tables?

**Comment by gaillard** [comment]
Fixed with the recent commit that updates the amalgamation :)
