### ISSUE TITLE
Runtime error when using *sql.DB.QueryContext with this driver

### ISSUE THREAD

**Issue by frank12268** [mattn/go-sqlite3#458]
When using (*sql.DB) QueryContext, *SQLiteRows.Close() and *SQLiteRows.Next() seem can be called simultaneously (by timeout context and main routine respectively).
*SQLiteRows.Next() might use a sqlite3_stmt which was disposed by *SQLiteRows.Close() before, thus the runtime error popped up.

**Comment by frank12268** [comment]
A simple way to reproduce this error in my box is
```
package main

import (
	"context"
	"database/sql"
	"fmt"
	"math/rand"
	"testing"
	"time"

	_ "github.com/mattn/go-sqlite3"
	"github.com/stretchr/testify/assert"
)

var (
	sqliteAddress       = "file::memory:?mode=memory&cache=shared"
	testTableStatements = []string{
		`DROP TABLE IF EXISTS test_table`,
		`
CREATE TABLE IF NOT EXISTS test_table (
	key1      VARCHAR(64) PRIMARY KEY,
	key_id    VARCHAR(64) NOT NULL,
	key2      VARCHAR(64) NOT NULL,
	key3      VARCHAR(64) NOT NULL,
	key4      VARCHAR(64) NOT NULL,
	key5      VARCHAR(64) NOT NULL,
	key6      VARCHAR(64) NOT NULL,
	data      BLOB        NOT NULL
);`,
	}
	letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
)

func randStringBytes(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = letterBytes[rand.Intn(len(letterBytes))]
	}
	return string(b)
}

func initDatabase(t *testing.T, db *sql.DB, rowCount int64) {
	t.Logf("Executing db initializing statements")
	for _, query := range testTableStatements {
		_, err := db.Exec(query)
		assert.Nil(t, err)
	}
	for i := int64(0); i < rowCount; i++ {
		query := `INSERT INTO test_table
			(key1, key_id, key2, key3, key4, key5, key6, data)
			VALUES
			(?, ?, ?, ?, ?, ?, ?, ?);`
		args := []interface{}{
			randStringBytes(50),
			fmt.Sprint(i),
			randStringBytes(50),
			randStringBytes(50),
			randStringBytes(50),
			randStringBytes(50),
			randStringBytes(50),
			randStringBytes(50),
			randStringBytes(2048),
		}
		_, err := db.Exec(query, args...)
		assert.Nil(t, err)
	}
}

func TestShortTimeout(t *testing.T) {
	t.Logf("Starting db...")
	db, err := sql.Open("sqlite3", sqliteAddress)
	assert.Nil(t, err)
	defer db.Close()
	initDatabase(t, db, 10000)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Microsecond)
	defer cancel()
	query := `SELECT key1, key_id, key2, key3, key4, key5, key6, data
		FROM test_table
		ORDER BY key2 ASC`
	rows, err := db.QueryContext(ctx, query)
	assert.Nil(t, err)
	defer rows.Close()
	for rows.Next() {
		var key1, keyid, key2, key3, key4, key5, key6 string
		var data []byte
		err = rows.Scan(&key1, &keyid, &key2, &key3, &key4, &key5, &key6, &data)
		if err != nil {
			break
		}
	}
	assert.Equal(t, context.DeadlineExceeded, ctx.Err())
	assert.NotNil(t, rows.Err())
}
```

The critical point here is to set the timeout ('10*time.Microsecond' in code piece) to be:
1. after `rows *sql.Rows` returns
2. before `for rows.Next()` loop finishes

**Comment by frank12268** [comment]
The log is:
```
$ go test ./ -v -run TestShortTimeout
=== RUN   TestShortTimeout
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x430e9d6]

runtime stack:
runtime.throw(0x44929f1, 0x2a)
    /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
    /usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 5 [syscall, locked to thread]:
runtime.cgocall(0x42d6500, 0xc42027ebd0, 0x0)
    /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42027eba0 sp=0xc42027eb60
<...omitted...>/vendor/github.com/mattn/go-sqlite3._Cfunc_sqlite3_reset(0x501f000, 0x0)
    <...omitted...>/vendor/github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:795 +0x49 fp=0xc42027ebd0 sp=0xc42027eba0
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next.func2(0x501f000, 0x100000000000009)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:934 +0x60 fp=0xc42027ec08 sp=0xc42027ebd0
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc4203e71d0, 0xc42001c280, 0x8, 0x8, 0x8, 0x8)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:934 +0xffe fp=0xc42027ed80 sp=0xc42027ec08
database/sql.(*Rows).nextLocked(0xc42001c100, 0xc42027edf8)
    /usr/local/go/src/database/sql/sql.go:2149 +0x6c fp=0xc42027edc0 sp=0xc42027ed80
database/sql.(*Rows).Next.func1()
    /usr/local/go/src/database/sql/sql.go:2134 +0x3c fp=0xc42027edf0 sp=0xc42027edc0
database/sql.withLock(0x46019a0, 0xc42001c130, 0xc42027ee38)
    /usr/local/go/src/database/sql/sql.go:2545 +0x65 fp=0xc42027ee18 sp=0xc42027edf0
database/sql.(*Rows).Next(0xc42001c100, 0x4497c10)
    /usr/local/go/src/database/sql/sql.go:2135 +0x83 fp=0xc42027ee68 sp=0xc42027ee18
<...omitted...>.TestShortTimeout(0xc420070c30)
    <...gopath...>/src/<...omitted...>/query_context_test.go:84 +0x293 fp=0xc42027efa8 sp=0xc42027ee68
testing.tRunner(0xc420070c30, 0x4497cd8)
    /usr/local/go/src/testing/testing.go:657 +0x96 fp=0xc42027efd0 sp=0xc42027efa8
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42027efd8 sp=0xc42027efd0
created by testing.(*T).Run
    /usr/local/go/src/testing/testing.go:697 +0x2ca

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420070b60, 0x4488fc3, 0x10, 0x4497cd8, 0x405b2d5)
    /usr/local/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc420070b60)
    /usr/local/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc420070b60, 0xc420053de0)
    /usr/local/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc4200e8fc0, 0x4627480, 0x1, 0x1, 0xc420053ed0)
    /usr/local/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc420053f20, 0xc420053f20)
    /usr/local/go/src/testing/testing.go:822 +0xfc
main.main()
    <...omitted...>/_test/_testmain.go:42 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [chan receive]:
database/sql.(*DB).connectionOpener(0xc42008db80)
    /usr/local/go/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
    /usr/local/go/src/database/sql/sql.go:582 +0x212

goroutine 10029 [semacquire]:
sync.runtime_Semacquire(0xc42001c138)
    /usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*RWMutex).Lock(0xc42001c130)
    /usr/local/go/src/sync/rwmutex.go:91 +0x6e
database/sql.(*Rows).close(0xc42001c100, 0x45ff1e0, 0x464e220, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:2422 +0x8e
database/sql.(*Rows).awaitDone(0xc42001c100, 0x4602fe0, 0xc420166880)
    /usr/local/go/src/database/sql/sql.go:2122 +0x8e
created by database/sql.(*Rows).initContextClose
    /usr/local/go/src/database/sql/sql.go:2116 +0x92

goroutine 10028 [syscall, locked to thread]:
<...omitted...>/vendor/github.com/mattn/go-sqlite3._Cfunc_sqlite3_errmsg(0x4806460, 0x0)
    <...omitted...>/vendor/github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:643 +0x4a
<...omitted...>/vendor/github.com/mattn/go-sqlite3.lastError.func3(0x4806460, 0xc400000009)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:414 +0x60
<...omitted...>/vendor/github.com/mattn/go-sqlite3.lastError(0x4806460, 0x0, 0x0)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:414 +0x7d
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteConn).lastError(0xc420018c30, 0x9, 0xc4204246c8)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:403 +0x2e
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteStmt).Close(0xc420505920, 0x0, 0x0)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:721 +0xd9
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Close(0xc4203e71d0, 0x0, 0xc42006f860)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:896 +0xbc
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteStmt).query.func2(0x47a5f58, 0xc42006f800, 0xc4203e71d0, 0x4806460)
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:827 +0x12d
created by <...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteStmt).query
    <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:831 +0x18d
exit status 2
FAIL    <...omitted...> 1.540s
```

**Comment by frank12268** [comment]
And one more in another box:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fedb87024c0]

runtime stack:
runtime.throw(0xcbf27d, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 754 [syscall, locked to thread]:
runtime.cgocall(0xa39880, 0xc420ae2e10, 0xcbdd3a)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420ae2dd0 sp=0xc420ae2d90
<...omitted...>/vendor/github.com/mattn/go-sqlite3._Cfunc_sqlite3_column_type(0x7fed8001b1f8, 0x7fed00000000, 0x0)
        <...omitted...>/vendor/github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:603 +0x4d fp=0xc420ae2e10 sp=0xc420ae2dd0
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next.func3(0x7fed8001b1f8, 0xc400000000, 0x2)
        <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:944 +0x68 fp=0xc420ae2e48 sp=0xc420ae2e10
<...omitted...>/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next(0xc42241a3c0, 0xc422499480, 0x2, 0x2, 0x431d1e, 0xc400000008)
        <...gopath...>/src/<...omitted...>/vendor/github.com/mattn/go-sqlite3/sqlite3.go:944 +0xb4 fp=0xc420ae2fc0 sp=0xc420ae2e48
database/sql.(*Rows).nextLocked(0xc420460580, 0xc420ae3038)
        /usr/local/go/src/database/sql/sql.go:2149 +0x6c fp=0xc420ae3000 sp=0xc420ae2fc0
database/sql.(*Rows).Next.func1()
        /usr/local/go/src/database/sql/sql.go:2134 +0x3c fp=0xc420ae3030 sp=0xc420ae3000
database/sql.withLock(0x130e6a0, 0xc4204605b0, 0xc420ae3078)
        /usr/local/go/src/database/sql/sql.go:2545 +0x65 fp=0xc420ae3058 sp=0xc420ae3030
database/sql.(*Rows).Next(0xc420460580, 0x91)
        /usr/local/go/src/database/sql/sql.go:2135 +0x83 fp=0xc420ae30a8 sp=0xc420ae3058

```

**Comment by frank12268** [comment]
The symptom looks like:
1. When context timeout, *SQLiteRows / *SQLiteStmt / *C.sqlite3_stmt get released
https://github.com/mattn/go-sqlite3/blob/a97e7bb12f7a08fabc155855e9861f983d6d7dec/sqlite3.go#L920
https://github.com/mattn/go-sqlite3/blob/a97e7bb12f7a08fabc155855e9861f983d6d7dec/sqlite3.go#L990
https://github.com/mattn/go-sqlite3/blob/a97e7bb12f7a08fabc155855e9861f983d6d7dec/sqlite3.go#L813
2. *SQLiteRows.Next visits those resources after that
https://github.com/mattn/go-sqlite3/blob/a97e7bb12f7a08fabc155855e9861f983d6d7dec/sqlite3.go#L1023
https://github.com/mattn/go-sqlite3/blob/a97e7bb12f7a08fabc155855e9861f983d6d7dec/sqlite3.go#L1015
https://github.com/mattn/go-sqlite3/blob/a97e7bb12f7a08fabc155855e9861f983d6d7dec/sqlite3.go#L1038
...

**Comment by frank12268** [comment]
Some extra info might needed:
**go version**
```
$ go version
go version go1.8.3 darwin/amd64
```
**library version**
```
{
    "checksumSHA1": "aXzeWoRG3sU38RYQnG7MpJUsGLY=",
    "path": "github.com/mattn/go-sqlite3",
    "revision": "3fa7ed217682f0f66953e3c37d7a648bbc5d3e5c",
    "revisionTime": "2017-06-14T13:22:40Z"
}
```
Though it is some older version, I think the problem should remain in the latest version.
**go env**
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="<...gopath...>"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/d_/17dg6drs2ss4yttxylv9bv3r0000gn/T/go-build079193703=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by mattn** [comment]
Could you please try this patch?

```diff
diff --git a/sqlite3.go b/sqlite3.go
index bff6b7c..5c02975 100644
--- a/sqlite3.go
+++ b/sqlite3.go
@@ -1020,6 +1020,9 @@ func (rc *SQLiteRows) DeclTypes() []string {
 
 // Next move cursor to next.
 func (rc *SQLiteRows) Next(dest []driver.Value) error {
+	if rc.closed {
+		return io.EOF
+	}
 	rv := C.sqlite3_step(rc.s.s)
 	if rv == C.SQLITE_DONE {
 		return io.EOF
```

**Comment by frank12268** [comment]
Thanks for your quick response.
Of course this patch will lower the possibility, but seems like not a ultimate solution.
I am not requesting for a solution in a short time, I myself fixed this by dealing with context outside this driver library.
Just post it to help to improve this library, and btw confirm my hypothesis

**Comment by mattn** [comment]
Thank you. I'll look into it in later.
