### ISSUE TITLE
segmentation violation calling go-sqlite3._Cfunc_sqlite3_step (on CentOS)

### ISSUE THREAD

**Issue by thisisaaronland** [mattn/go-sqlite3#553]
This _appears_ to be a CentOS (centos-release-7-4.1708.el7.centos.x86_64) specific issue since I can't reproduce it on either OS X or Ubuntu.

The problem manifests itself using the following code, which has a fresh vendored copy of `go-sqlite3` as 20a06cb34cf7c9846f3ea217c1cecb552aa6bf20:

https://github.com/whosonfirst/go-whosonfirst-pip-v2/blob/centos/cmd/wof-pip-server.go
https://github.com/whosonfirst/go-whosonfirst-pip-v2/blob/centos/index/spatialite.go

And the following data:

https://dist.whosonfirst.org/sqlite/#whosonfirst-data-latest.db

Note that the `whosonfirst-data-latest.db` is pretty huge so you can also test with this (the other distributions don't have spatial tables yet):

https://dist.whosonfirst.org/sqlite/#whosonfirst-data-constituency-us-latest.db

Invoked as follows:

```
./bin/wof-pip-server -mode spatialite -index spatialite -cache spatialite -spatialite-dsn /usr/local/data/db/whosonfirst-data-latest.db 
```

Which starts up with the following output:

```
SpatiaLite version ..: 4.1.1	Supported Extensions:
	- 'VirtualShape'	[direct Shapefile access]
	- 'VirtualDbf'		[direct DBF access]
	- 'VirtualXL'		[direct XLS access]
	- 'VirtualText'		[direct CSV/TXT access]
	- 'VirtualNetwork'	[Dijkstra shortest path]
	- 'RTree'		[Spatial Index - R*Tree]
	- 'MbrCache'		[Spatial Index - MBR cache]
	- 'VirtualSpatialIndex'	[R*Tree metahandler]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualFDO'		[FDO-OGR interoperability]
	- 'SpatiaLite'		[Spatial SQL - OGC]
PROJ.4 version ......: Rel. 4.8.0, 6 March 2012
GEOS version ........: 3.4.2-CAPI-1.8.2 r3921
SpatiaLite version ..: 4.1.1	Supported Extensions:
	- 'VirtualShape'	[direct Shapefile access]
	- 'VirtualDbf'		[direct DBF access]
	- 'VirtualXL'		[direct XLS access]
	- 'VirtualText'		[direct CSV/TXT access]
	- 'VirtualNetwork'	[Dijkstra shortest path]
	- 'RTree'		[Spatial Index - R*Tree]
	- 'MbrCache'		[Spatial Index - MBR cache]
	- 'VirtualSpatialIndex'	[R*Tree metahandler]
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualFDO'		[FDO-OGR interoperability]
	- 'SpatiaLite'		[Spatial SQL - OGC]
PROJ.4 version ......: Rel. 4.8.0, 6 March 2012
GEOS version ........: 3.4.2-CAPI-1.8.2 r3921
```

However when I query the server like this:

```
curl 'localhost:8080?latitude=37.617699&longitude=-122.381859'
```

It (the server) panics as follows:

```
10:18:05.238030 [wof-pip-server] STATUS listening for requests on localhost:8080
2018/04/18 10:18:17 SELECT id FROM geometries WHERE ST_Within(GeomFromText('POINT(-122.381859 37.617699)'), geom)
		          AND rowid IN (
			    SELECT pkid FROM idx_geometries_geom WHERE xmin < -122.381859 AND xmax > -122.381859 AND ymin < 37.617699 AND ymax > 37.617699
                          )
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7fd0ea95deff]

runtime stack:
runtime.throw(0x943115, 0x2a)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 16 [syscall]:
runtime.cgocall(0x7aaff0, 0xc420069760, 0x1)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420069730 sp=0xc4200696f8 pc=0x40cbc4
github.com/whosonfirst/go-whosonfirst-sqlite/vendor/github.com/mattn/go-sqlite3._Cfunc_sqlite3_step(0x7fd0dc007a38, 0x7fd000000000)
	_cgo_gotypes.go:1019 +0x49 fp=0xc420069760 sp=0xc420069730 pc=0x756ab9
github.com/whosonfirst/go-whosonfirst-sqlite/vendor/github.com/mattn/go-sqlite3.(*SQLiteRows).Next.func1(0x7fd0dc007a38, 0x967950)
	/usr/local/whosonfirst/go-whosonfirst-pip-v2/src/github.com/whosonfirst/go-whosonfirst-sqlite/vendor/github.com/mattn/go-sqlite3/sqlite3.go:1269 +0x56 fp=0xc420069798 sp=0xc420069760 pc=0x766896

...and so on
```

I can make the same query directly from sqlite3 (loading the spatialite extension, installed via `yum`) without any problems, though:

```
sqlite3 /usr/local/data/db/whosonfirst-data-latest.db 
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
load 'libspatialite'
sqlite> SELECT id FROM geometries WHERE ST_Within(GeomFromText('POINT(-122.727802 37.784969)'), geom) AND rowid IN ( SELECT pkid FROM idx_geometries_geom WHERE xmin < -122.727802 AND xmax > -122.727802 AND ymin < 37.784969 AND ymax > 37.784969 );
0
404528711
```

Any idea what might be going on here?

**Comment by mattn** [comment]
Could you please small example to reproduce?

**Comment by thisisaaronland** [comment]
I haven't forgotten about but life has gotten a bit hectic and I will get to it soon. Is the `whosonfirst-data-constituency-us-latest.db.bz2` (300MB) too big?

https://dist.whosonfirst.org/sqlite/whosonfirst-data-constituency-us-latest.db.bz2

**Comment by mattn** [comment]
I could scan all rows in geometries  without spatialite. As far as I can see the log you mentioned, I guess it crash in spatialite.

**Comment by mattn** [comment]
I tested your database.

```go
package main

import (
	"database/sql"
	"errors"
	"fmt"
	"log"

	"github.com/mattn/go-sqlite3"
)

var LibNames = []struct {
	lib  string
	proc string
}{
	{"mod_spatialite", "sqlite3_modspatialite_init"},
	{"mod_spatialite.dylib", "sqlite3_modspatialite_init"},
	{"libspatialite.so", "sqlite3_modspatialite_init"},
	{"libspatialite.so", "spatialite_init_ex"},
}

func main() {
	sql.Register("spatialite", &sqlite3.SQLiteDriver{
		ConnectHook: func(conn *sqlite3.SQLiteConn) error {
			for _, v := range LibNames {
				err := conn.LoadExtension(v.lib, v.proc)
				if err == nil { //|| err.Error() == "not an error" {
					return nil
				}
				println(err.Error())
			}
			return errors.New("bad")
		},
	})
	db, err := sql.Open("spatialite", "whosonfirst-data-constituency-us-latest.db")
	if err != nil {
		log.Fatal(err)
	}
	rows, err := db.Query(`SELECT id FROM geometries WHERE ST_Within(GeomFromText('POINT(-122.727802 37.784969)'), geom) AND rowid IN ( SELECT pkid FROM idx_geometries_geom WHERE xmin < -122.727802 AND xmax > -122.727802 AND ymin < 37.784969 AND ymax > 37.784969 );`)
	if err != nil {
		log.Fatal(err)
	}
	for rows.Next() {
		var id string
		err = rows.Scan(&id)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(id)
	}
}
```
I don't see any errors.

**Comment by GJRTimmer** [comment]
Provided code works.

@thisisaaronland can you test it with Spatialite 4.3.0a (Current Version) not with the one from YUM.

Will close until re-open is required.
