### ISSUE TITLE
segfault on go1.11.1

### ISSUE THREAD

**Issue by yonderblue** [mattn/go-sqlite3#649]
Anyone tested on go1.11.1 yet?
I'm getting
```
unexpected fault address 0x4e00
20:26:31 			fatal error: fault
20:26:31 			[signal SIGSEGV: segmentation violation code=0x1 addr=0x4e00 pc=0x12812b9]
20:26:31 			
20:26:31 			goroutine 114767 [running]:
20:26:31 			runtime.throw(0x4c3de2, 0x2)
20:26:31 				/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0x7faea93caae0 sp=0x7faea93caab0 pc=0x497d42
20:26:31 			runtime.recordForPanic(0x2aca5bc, 0x3, 0x3)
20:26:31 				/usr/local/go/src/runtime/print.go:53 +0x12e fp=0x7faea93cab18 sp=0x7faea93caae0 pc=0x49870e
20:26:31 			runtime.gwrite(0x2aca5bc, 0x3, 0x3)
20:26:31 				/usr/local/go/src/runtime/print.go:93 +0x113 fp=0x7faea93cab50 sp=0x7faea93cab18 pc=0x498933
20:26:31 			runtime.printstring(0x7faea93cabd8, 0x4bece2)
20:26:31 				/usr/local/go/src/runtime/print.go:237 +0x78 fp=0x7faea93caba0 sp=0x7faea93cab50 pc=0x4990c8
20:26:31 			runtime.goroutineheader(0x497d42)
20:26:31 				/usr/local/go/src/runtime/traceback.go:917 +0x16f fp=0x7faea93cabe8 sp=0x7faea93caba0 pc=0x4bfe9f
20:26:31 			runtime.dopanic_m(0xc002a07080, 0x497d42, 0x7faea93caab0, 0x2acbe3c)
20:26:31 				/usr/local/go/src/runtime/panic.go:798 +0x30d fp=0x7faea93cac50 sp=0x7faea93cabe8 pc=0x4984ad
20:26:31 			runtime.fatalthrow.func1()
20:26:31 				/usr/local/go/src/runtime/panic.go:663 +0x5f fp=0x7faea93cac98 sp=0x7faea93cac50 pc=0x4c5b8f
20:26:31 			runtime.systemstack(0x7faea93cacb0)
20:26:31 				/usr/local/go/src/runtime/asm_amd64.s:351 +0x66 fp=0x7faea93caca0 sp=0x7faea93cac98 pc=0x4c6e96
20:26:31 			runtime.mstart()
20:26:31 				/usr/local/go/src/runtime/proc.go:1229 fp=0x7faea93caca8 sp=0x7faea93caca0 pc=0x49c650
20:26:31 			created by database/sql.(*Rows).initContextClose
20:26:31 				/usr/local/go/src/database/sql/sql.go:2613 +0xfa
```

**Comment by mattn** [comment]
What OS do you use? Please show me small code to reproduce.

**Comment by gaillard** [comment]
I do not have a small repro, only big one :/ However this might be only related to https://github.com/golang/go/issues/28109.

**Comment by GJRTimmer** [comment]
Closable ?

**Comment by DmitriyMV** [comment]
Kindly ping @yonderblue - can we close this?

**Comment by mattn** [comment]
Please reopen issue if you still have problem. Thanks.
